# Generated by Django 3.2.8 on 2023-06-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('categories', models.JSONField(null=True)),
                ('tags', models.JSONField(null=True)),
                ('mdfile', models.TextField()),
            ],
        ),
    ]
