# Generated by Django 3.2.8 on 2023-06-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mdfile',
            field=models.FilePathField(match='.*\\.md$', path='/home/zzf/markdown'),
        ),
    ]
